My name is Ingy döt Net. I am an Acmeist computer programmer. These are my projects...

^ "Acmeism"[/acmeism]

These projects are all Programmer Acmeist, meaning they are not confined by programming language borders. They are either implemented in many programming languages or facilitate implementing other things in many programming languages.

* "YAML"[/yaml]
* "JSYNC"[/jsync]
* "C'Dent"[/cdent]
* "TestML"[/testml]
* "Stardoc"[/stardoc]
* "Jemplate"[/jemplate]
* "pQuery"[/pquery]

^ "Perl"[/perl]

Many of my projects are implemented in Perl even though they are not specific to Perl. These are the projects that _are_ specific to Perl.

* "Inline"[/inline]
* "IO::All"[/io-all]
* "XXX"[/xxx]
* "YAML-*"[/yaml-pm]

^ Python

* "Package"[/package]
* "PyPlay"[/pyplay]

^ JavaScript

* "Class"[/class-js]
* "XY"[/xy]

^ Language

* HelloWord
* ZhongBei

^ Social Software

* "CogLife"[/coglife]
* "CogBase"[/cogbase]
* "Kwiki"[/kwiki]
* "XLogger"[/xlogger]
* "Vroom"[/vroom]
* "Wikiwyg"[/wikiwyg]
* "Socialtext"[/socialtext]

^ Web

* "Project Site"[/project-site]
* "Ingy's Web Sites"[/web-sites]

^ OPP

* "Tiddlyweb"[/tiddlyweb]
* "Tor"[/tor]
