My name is Ingy döt Net. I am an "Acmeist Computer Programmer"[/acmeism]. These are my projects...

^ Acmeism

These projects are all Programmer Acmeist, meaning they are not confined by programming language borders. They are either implemented in many programming languages or facilitate implementing other things in many programming languages.

* "YAML"[/yaml]
* "JSYNC"[/jsync]
* "C'Dent"[/cdent]
* "TestML"[/testml]
* "Stardoc"[/stardoc]
* "Jemplate"[/jemplate]
* "pQuery"[/pquery]

^ Social Software

These are all bigger, social software projects.

* "CogLife"[/coglife]
* "CogBase"[/cogbase]
* "Kwiki"[/kwiki]
* "XLogger"[/xlogger]
* "Vroom"[/vroom]
* "Wikiwyg"[/wikiwyg]
* "Socialtext"[/socialtext]

^ "Perl"[/perl]

Many of my projects are implemented in Perl even though they are not specific to Perl. These are the projects that _are_ specific to Perl.

* "YAML.pm"[/yaml-pm]
* "YAML::XS"[/yaml-xs]
* "Inline"[/inline]
* "IO::All"[/io-all]
* "Test::Base"[/test-base]
* "Class::Field"[/class-field]
* "Perldoc"[/perldoc]
* "XXX.pm"[/xxx]
* "errors.pm"[/errors]
* "boolean.pm"[/boolean]

^ Python

Many of my new Acmeist tools are implemented in Python, but these projects are specific to Perl.

* "Package"[/package]
* "PyPlay"[/pyplay]

^ JavaScript

These projects are specific to JavaScript.

* "Test.Base"[/test-base]
* "Class"[/class-js]
* "XY"[/xy]

^ Natural Language

These projects are about learning natural languages.

* "HelloWord"[/helloword]
* "中貝"[/zhongbei]

^ Other Stuff

* "yaml.vim"[/yaml-vim]
* "Project Site"[/project-site]
* "Ingy's Web Sites"[/web-sites]

^ OPP

Yeah, you know me...

* "Tiddlyweb"[/tiddlyweb]
* "Tor"[/tor]
