My name is Ingy döt Net. I am an "Acmeist Computer Programmer"[/acmeism]. These are my projects...

^ Acmeism

These projects are all Programmer Acmeist, meaning they are not confined by programming language borders. They are either implemented in many programming languages or facilitate implementing other things in many programming languages.

* "YAML"[/yaml] - YAML Ain't Markup Language
* "JSYNC"[/jsync] - JSON + YAML = Awesome
* "C'Dent"[/cdent] - Portable Module Programming Language
* "TestML"[/testml] - Data Driven Unit Testing for All Languages
* "Stardoc"[/stardoc] - Portable Documentation Format
* "Jemplate"[/jemplate] - Template Toolkit for All Languages
* "pQuery"[/pquery] - JQuery for Server Languages
* "YeS"[/yes] - YAML/JSON Schema Language
* "reParse"[/reparse] - Parser Built From Regular Expressions

^ Social Software

These are all bigger, social software projects.

* "CogLife"[/coglife] - Virtual World for the Social Web
* "CogBase"[/cogbase] - Modern Data Storage System
* "Kwiki"[/kwiki] - Perl Wiki made entirely of Plugins
* "XLogger"[/xlogger] - Git Based Blogging
* "Vroom"[/vroom] - Slideshows in Vim
* "Wikiwyg"[/wikiwyg] - Multimode Web Editor
* "Kwim"[/kwim] - Know What I Mean?
* "BPAN"[/bpan] - Better Programmers, Acmeism Needs

^ Perl

Many of my projects are implemented in Perl even though they are not specific to Perl. These are the projects that _are_ specific to Perl.

* "YAML.pm"[/yaml-pm] - The Original YAML for Perl
* "YAML::XS"[/yaml-xs] - The Better/Faster YAML for Perl
* "Inline"[/inline] - Use Other Languages in Perl
* "IO::All"[/io-all] - Simplify All I/O in Perl
* "Test::Base"[/test-base] - Data Driven Unit Testing
* "Class::Field"[/class-field] - Perl OO Accessor Generator
* "Perldoc"[/perldoc] - Wiki Replacement for POD
* "XXX.pm"[/xxx] - See Your Perl Data in the Nude
* "errors.pm"[/errors] - Try/Catch for Perl
* "boolean.pm"[/boolean] - Booleans for Perl

^ Python

Many of my new Acmeist tools are implemented in Python, but these projects are specific to Python.

* "Package"[/package] - Package Building Sanity for Python
* "PyPlay"[/pyplay] - Mo Better Interactive Python

^ JavaScript

These projects are specific to JavaScript.

* "Test.Base"[/test-base] - Data Driven Unit Testing
* "Class"[/class-js] - Class to Generate Classes in JS
* "XY"[/xy] - Google Maps-esque Canvas in JS

^ Natural Language

These projects are about learning natural languages.

* "HelloWord"[/helloword] - Learn 200 Common Words in 20 Languages
* "中貝"[/zhongbei] - The Chinese Shell

^ Other Stuff

* "AYCABTU"[/aycabtu] - All Your Codes Are Belong To Us
* "NoCore"[/nocore] - Zero CPU Computing
* "yaml.vim"[/yaml-vim] - YAML Syntax Hilighting for Vim
* "Project Site"[/project-site] - Quick Builder for Sites Like This One
* "Ingy's Web Sites"[/web-sites] - All My Sites Are Belong To You
* "DotDotDot"[/dotdotdot] - Organize and Share Your Unix Dot Files

^ OPP

Yeah, you know me...

* "Socialtext"[/socialtext] - An Enterprise Wiki
* "Tiddlyweb"[/tiddlyweb] - TiddlyWiki storage system
* "Tor"[/tor] - The Onion Router
